-- ============================================================
-- Migration 002: plan_feedback table
--
-- Stretch goal: stores scientist corrections to AI-generated plans.
-- Each row is one correction to one section of one plan.
-- The embedding enables RAG retrieval: when generating a new plan,
-- we find the most similar past corrections and inject them as
-- few-shot examples into the agent prompts.
--
-- This table is what makes Praxis a PLATFORM not just a tool.
-- Every correction compounds: each one improves every future plan
-- of the same type.
-- ============================================================

CREATE TABLE IF NOT EXISTS plan_feedback (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Reference to the plan that was corrected
  -- CASCADE: if a plan is deleted, its feedback goes with it
  plan_id           UUID REFERENCES experiment_plans(id) ON DELETE CASCADE,

  -- Who made the correction
  reviewer          TEXT DEFAULT 'anonymous',

  -- Which section of the plan was corrected
  section           TEXT NOT NULL CHECK (section IN (
                      'protocol',
                      'materials',
                      'budget',
                      'timeline',
                      'validation'
                    )),

  -- Rating of the original AI output (1 = very wrong, 5 = very good)
  -- We only RAG-retrieve corrections where rating <= 3
  -- (i.e. the AI actually needed correcting)
  rating            SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),

  -- The correction itself
  original_content  TEXT NOT NULL,   -- exact AI output text that was wrong
  correction        TEXT NOT NULL,   -- what the scientist changed it to
  correction_reason TEXT DEFAULT '', -- why the AI output was wrong

  -- Retrieval tags (used to filter before similarity search)
  experiment_type   TEXT DEFAULT '', -- e.g. 'FITC-dextran gut permeability'
  domain            TEXT DEFAULT 'other' CHECK (domain IN (
                      'diagnostics',
                      'gut_health',
                      'cell_biology',
                      'climate',
                      'other'
                    )),

  -- Embedding of the correction text (384-dim)
  -- Generated by generate_embeddings.js or backend on feedback submit
  embedding         vector(384),

  -- Tracking: how many times this correction has been used as few-shot
  applied_count     INTEGER NOT NULL DEFAULT 0
);

COMMENT ON TABLE plan_feedback IS
  'Scientist corrections to AI-generated plan sections. Powers the RAG feedback loop.';
COMMENT ON COLUMN plan_feedback.rating IS
  '1-5 rating of original AI output. Only corrections with rating <= 3 are RAG-retrieved.';
COMMENT ON COLUMN plan_feedback.applied_count IS
  'Incremented each time this correction is injected as a few-shot example.';

